"""Unit conversion utilities for FeaGPT."""

import re
import logging

logger = logging.getLogger(__name__)


class UnitConverter:
    """Engineering unit conversion with automatic detection."""

        CONVERSIONS = {
                    # Length -> meters
                            "mm": 1e-3, "cm": 1e-2, "m": 1.0, "in": 0.0254, "ft": 0.3048,
                                    # Force -> Newtons
                                            "N": 1.0, "kN": 1e3, "MN": 1e6, "lbf": 4.44822,
                                                    # Pressure -> Pascals
                                                            "Pa": 1.0, "kPa": 1e3, "MPa": 1e6, "GPa": 1e9,
                                                                    "psi": 6894.76, "ksi": 6.89476e6, "bar": 1e5, "atm": 101325,
                                                                            # Density -> kg/m3
                                                                                    "kg/m3": 1.0, "g/cm3": 1000.0, "lb/in3": 27679.9,
                                                                                            "tonne/mm3": 1e12,
                                                                                                    # Angular velocity -> rad/s
                                                                                                            "rpm": 0.10472, "rad/s": 1.0, "deg/s": 0.017453,
                                                                                                                    # Temperature -> Kelvin
                                                                                                                            "K": 1.0,
                                                                                                                                }

                                                                                                                                    # Unit categories
                                                                                                                                        LENGTH_UNITS = {"mm", "cm", "m", "in", "ft"}
                                                                                                                                            FORCE_UNITS = {"N", "kN", "MN", "lbf"}
                                                                                                                                                PRESSURE_UNITS = {"Pa", "kPa", "MPa", "GPa", "psi", "ksi", "bar", "atm"}
                                                                                                                                                    DENSITY_UNITS = {"kg/m3", "g/cm3", "lb/in3", "tonne/mm3"}
                                                                                                                                                        ANGULAR_UNITS = {"rpm", "rad/s", "deg/s"}

                                                                                                                                                            @classmethod
                                                                                                                                                                def convert(cls, value, from_unit, to_unit):
                                                                                                                                                                        """Convert value between units."""
                                                                                                                                                                                if from_unit == to_unit:
                                                                                                                                                                                                return value
                                                                                                                                                                                                        if from_unit not in cls.CONVERSIONS or to_unit not in cls.CONVERSIONS:
                                                                                                                                                                                                                        logger.warning(f"Unknown unit: {from_unit} or {to_unit}")
                                                                                                                                                                                                                                    return value
                                                                                                                                                                                                                                            # Convert to SI base, then to target
                                                                                                                                                                                                                                                    si_value = value * cls.CONVERSIONS[from_unit]
                                                                                                                                                                                                                                                            return si_value / cls.CONVERSIONS[to_unit]

                                                                                                                                                                                                                                                                @classmethod
                                                                                                                                                                                                                                                                    def to_si(cls, value, unit):
                                                                                                                                                                                                                                                                                """Convert to SI base unit."""
                                                                                                                                                                                                                                                                                        if unit in cls.CONVERSIONS:
                                                                                                                                                                                                                                                                                                        return value * cls.CONVERSIONS[unit]
                                                                                                                                                                                                                                                                                                                return value

                                                                                                                                                                                                                                                                                                                    @classmethod
                                                                                                                                                                                                                                                                                                                        def parse_value_with_unit(cls, text):
                                                                                                                                                                                                                                                                                                                                    """Parse a string like '500 MPa' or '200mm' into (value, unit)."""
                                                                                                                                                                                                                                                                                                                                            match = re.match(r'([+-]?\d*\.?\d+(?:[eE][+-]?\d+)?)\s*(\w+/?[\w]*)', text.strip())
                                                                                                                                                                                                                                                                                                                                                    if match:
                                                                                                                                                                                                                                                                                                                                                                    value = float(match.group(1))
                                                                                                                                                                                                                                                                                                                                                                                unit = match.group(2)
                                                                                                                                                                                                                                                                                                                                                                                            return value, unit
                                                                                                                                                                                                                                                                                                                                                                                                    return None, None

                                                                                                                                                                                                                                                                                                                                                                                                        @classmethod
                                                                                                                                                                                                                                                                                                                                                                                                            def rpm_to_rad_s(cls, rpm):
                                                                                                                                                                                                                                                                                                                                                                                                                        """Convert RPM to rad/s."""
                                                                                                                                                                                                                                                                                                                                                                                                                                import math
                                                                                                                                                                                                                                                                                                                                                                                                                                        return rpm * 2 * math.pi / 60

                                                                                                                                                                                                                                                                                                                                                                                                                                            @classmethod
                                                                                                                                                                                                                                                                                                                                                                                                                                                def celsius_to_kelvin(cls, celsius):
                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Convert Celsius to Kelvin."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return celsius + 273.15
        }