"""
Surrogate modeling module for FeaGPT.

Builds lightweight surrogate models from FEA results
for rapid design space interpolation and prediction.

References:
    Rasmussen & Williams, Gaussian Processes for ML (MIT Press, 2006)
        Pedregosa et al., JMLR 12, 2825 (2011)
        """

        import numpy as np
        import pandas as pd
        import logging
        from typing import Dict, List, Tuple, Optional
        from dataclasses import dataclass

        logger = logging.getLogger(__name__)


        @dataclass
        class SurrogateMetrics:
            """Surrogate model quality metrics."""
                model_type: str
                    r2_score: float
                        rmse: float
                            max_error: float
                                cv_r2_mean: float = 0.0
                                    cv_r2_std: float = 0.0
                                        n_training: int = 0
                                            n_features: int = 0


                                            class SurrogateModeler:
                                                """
                                                    Surrogate model builder for FEA design space interpolation.
                                                        
                                                            Supports GPR, Random Forest, and Polynomial regression.
                                                                Auto-selects best model via cross-validation.
                                                                    """

                                                                        def __init__(self, model_type: str = "auto"):
                                                                                self.model_type = model_type
                                                                                        self.model = None
                                                                                                self.scaler_x = None
                                                                                                        self.scaler_y = None
                                                                                                                self.metrics = None
                                                                                                                        self.feature_names = []
                                                                                                                                self.target_name = ""

                                                                                                                                    def fit(self, data: pd.DataFrame, feature_columns: List[str],
                                                                                                                                                target_column: str, test_fraction: float = 0.2) -> SurrogateMetrics:
                                                                                                                                                        """Train surrogate model on simulation data."""
                                                                                                                                                                from sklearn.preprocessing import StandardScaler
                                                                                                                                                                        from sklearn.model_selection import cross_val_score, train_test_split
                                                                                                                                                                                from sklearn.metrics import r2_score, mean_squared_error
                                                                                                                                                                                
                                                                                                                                                                                        self.feature_names = feature_columns
                                                                                                                                                                                                self.target_name = target_column
                                                                                                                                                                                                
                                                                                                                                                                                                        X = data[feature_columns].values.astype(float)
                                                                                                                                                                                                                y = data[target_column].values.astype(float)
                                                                                                                                                                                                                
                                                                                                                                                                                                                        self.scaler_x = StandardScaler()
                                                                                                                                                                                                                                self.scaler_y = StandardScaler()
                                                                                                                                                                                                                                        X_scaled = self.scaler_x.fit_transform(X)
                                                                                                                                                                                                                                                y_scaled = self.scaler_y.fit_transform(y.reshape(-1, 1)).ravel()
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                        X_train, X_test, y_train, y_test = train_test_split(
                                                                                                                                                                                                                                                                        X_scaled, y_scaled, test_size=test_fraction, random_state=42)

                                                                                                                                                                                                                                                                                if self.model_type == "auto":
                                                                                                                                                                                                                                                                                            best_model, best_type, _ = self._auto_select(X_train, y_train, X_test, y_test)
                                                                                                                                                                                                                                                                                                        self.model = best_model
                                                                                                                                                                                                                                                                                                                    model_type_used = best_type
                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                            self.model = self._create_model(self.model_type)
                                                                                                                                                                                                                                                                                                                                                        self.model.fit(X_train, y_train)
                                                                                                                                                                                                                                                                                                                                                                    model_type_used = self.model_type

                                                                                                                                                                                                                                                                                                                                                                            y_pred = self.model.predict(X_test)
                                                                                                                                                                                                                                                                                                                                                                                    r2 = r2_score(y_test, y_pred)
                                                                                                                                                                                                                                                                                                                                                                                            rmse = np.sqrt(mean_squared_error(y_test, y_pred)) * self.scaler_y.scale_[0]
                                                                                                                                                                                                                                                                                                                                                                                                    max_err = np.max(np.abs(y_test - y_pred)) * self.scaler_y.scale_[0]

                                                                                                                                                                                                                                                                                                                                                                                                            cv_scores = cross_val_score(
                                                                                                                                                                                                                                                                                                                                                                                                                            self._create_model(model_type_used), X_scaled, y_scaled, cv=5, scoring='r2')

                                                                                                                                                                                                                                                                                                                                                                                                                                    self.metrics = SurrogateMetrics(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    model_type=model_type_used, r2_score=r2, rmse=rmse,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                max_error=max_err, cv_r2_mean=cv_scores.mean(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cv_r2_std=cv_scores.std(), n_training=len(X_train),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        n_features=len(feature_columns))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.info(f"Surrogate ({model_type_used}): R2={r2:.4f}, RMSE={rmse:.4f}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return self.metrics

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def predict(self, params: Dict[str, float]) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Predict output for given parameter values."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if self.model is None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                raise RuntimeError("Model not fitted")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        x = np.array([[params[f] for f in self.feature_names]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                x_scaled = self.scaler_x.transform(x)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        y_scaled = self.model.predict(x_scaled)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return float(self.scaler_y.inverse_transform(y_scaled.reshape(-1, 1)).ravel()[0])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def predict_batch(self, param_df: pd.DataFrame) -> np.ndarray:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Predict for multiple configurations."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if self.model is None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise RuntimeError("Model not fitted")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                X = param_df[self.feature_names].values.astype(float)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        X_scaled = self.scaler_x.transform(X)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                y_scaled = self.model.predict(X_scaled)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return self.scaler_y.inverse_transform(y_scaled.reshape(-1, 1)).ravel()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def _create_model(self, model_type: str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Create a model instance by type."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if model_type == "gpr":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                from sklearn.gaussian_process import GaussianProcessRegressor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from sklearn.gaussian_process.kernels import RBF, ConstantKernel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return GaussianProcessRegressor(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            kernel=ConstantKernel(1.0) * RBF(1.0), alpha=1e-6, n_restarts_optimizer=5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif model_type == "rf":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                from sklearn.ensemble import RandomForestRegressor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return RandomForestRegressor(n_estimators=100, random_state=42)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif model_type == "polynomial":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                from sklearn.pipeline import Pipeline
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from sklearn.preprocessing import PolynomialFeatures
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from sklearn.linear_model import Ridge
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return Pipeline([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ('poly', PolynomialFeatures(degree=3, include_bias=False)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ('ridge', Ridge(alpha=1.0))])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise ValueError(f"Unknown model type: {model_type}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def _auto_select(self, X_train, y_train, X_test, y_test):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """Auto-select best model via test R2."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                from sklearn.metrics import r2_score
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        best_model, best_type, best_score = None, "", -float('inf')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for mtype in ["rf", "polynomial", "gpr"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            model = self._create_model(mtype)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            model.fit(X_train, y_train)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            score = r2_score(y_test, model.predict(X_test))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if score > best_score:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                best_score, best_model, best_type = score, model, mtype
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logger.warning(f"{mtype} failed: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return best_model, best_type, best_score

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def feature_importance(self) -> Optional[Dict[str, float]]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Get feature importance (RF only)."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if self.model and hasattr(self.model, 'feature_importances_'):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return dict(zip(self.feature_names, self.model.feature_importances_))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                        ))