"""Configuration management for FeaGPT."""

import os
import yaml
from dataclasses import dataclass, field
from typing import Optional
from pathlib import Path


@dataclass
class LLMConfig:
    provider: str = "gemini"
        model: str = "gemini-2.5-pro"
            api_key: str = ""
                temperature: float = 0.1
                    max_tokens: int = 8192


                    @dataclass
                    class KnowledgeBaseConfig:
                        embedding_model: str = "all-MiniLM-L6-v2"
                            embedding_dim: int = 384
                                similarity_threshold: float = 0.85
                                    materials_path: str = "knowledge/materials.json"
                                        geometry_patterns_path: str = "knowledge/geometry_patterns.json"
                                            solver_configs_path: str = "knowledge/solver_configs.json"


                                            @dataclass
                                            class MeshLevelConfig:
                                                min_size: float = 0.5
                                                    max_size: float = 3.0
                                                        description: str = ""


                                                        @dataclass
                                                        class MeshConfig:
                                                            backend: str = "gmsh"
                                                                levels: dict = field(default_factory=dict)
                                                                    default_level: str = "fine"
                                                                        element_type: str = "C3D10"


                                                                        @dataclass
                                                                        class GeometryConfig:
                                                                            output_format: str = "step"
                                                                                freecad_path: Optional[str] = None
                                                                                    tolerance_mm: float = 0.1
                                                                                        blacklisted_operations: list = field(default_factory=list)


                                                                                        @dataclass
                                                                                        class SimulationConfig:
                                                                                            solver: str = "calculix"
                                                                                                calculix_path: str = "ccx"
                                                                                                    max_iterations: int = 100
                                                                                                        convergence_tolerance: float = 1.0e-6
                                                                                                            output_format: str = "frd"


                                                                                                            @dataclass
                                                                                                            class BatchConfig:
                                                                                                                max_workers: int = 10
                                                                                                                    max_batch_size: int = 500
                                                                                                                        memory_per_case_mb: int = 512
                                                                                                                            retry_count: int = 3
                                                                                                                                isolation: bool = True


                                                                                                                                @dataclass
                                                                                                                                class OutputConfig:
                                                                                                                                    directory: str = "results"
                                                                                                                                        save_intermediate: bool = True
                                                                                                                                            plot_format: str = "png"
                                                                                                                                                dpi: int = 300


                                                                                                                                                class FeaGPTConfig:
                                                                                                                                                    """Central configuration for FeaGPT."""

                                                                                                                                                        def __init__(self, config_path: Optional[str] = None):
                                                                                                                                                                self.llm = LLMConfig()
                                                                                                                                                                        self.knowledge_base = KnowledgeBaseConfig()
                                                                                                                                                                                self.mesh = MeshConfig()
                                                                                                                                                                                        self.geometry = GeometryConfig()
                                                                                                                                                                                                self.simulation = SimulationConfig()
                                                                                                                                                                                                        self.batch = BatchConfig()
                                                                                                                                                                                                                self.output = OutputConfig()

                                                                                                                                                                                                                        if config_path:
                                                                                                                                                                                                                                    self.load(config_path)
                                                                                                                                                                                                                                            self._resolve_env_vars()

                                                                                                                                                                                                                                                def load(self, config_path: str):
                                                                                                                                                                                                                                                        """Load configuration from YAML file."""
                                                                                                                                                                                                                                                                path = Path(config_path)
                                                                                                                                                                                                                                                                        if not path.exists():
                                                                                                                                                                                                                                                                                    raise FileNotFoundError(f"Config file not found: {config_path}")

                                                                                                                                                                                                                                                                                            with open(path) as f:
                                                                                                                                                                                                                                                                                                        raw = yaml.safe_load(f)

                                                                                                                                                                                                                                                                                                                if "llm" in raw:
                                                                                                                                                                                                                                                                                                                            for k, v in raw["llm"].items():
                                                                                                                                                                                                                                                                                                                                            if hasattr(self.llm, k):
                                                                                                                                                                                                                                                                                                                                                                setattr(self.llm, k, v)

                                                                                                                                                                                                                                                                                                                                                                        if "knowledge_base" in raw:
                                                                                                                                                                                                                                                                                                                                                                                    for k, v in raw["knowledge_base"].items():
                                                                                                                                                                                                                                                                                                                                                                                                    if hasattr(self.knowledge_base, k):
                                                                                                                                                                                                                                                                                                                                                                                                                        setattr(self.knowledge_base, k, v)

                                                                                                                                                                                                                                                                                                                                                                                                                                if "meshing" in raw:
                                                                                                                                                                                                                                                                                                                                                                                                                                            if "levels" in raw["meshing"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.mesh.levels = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name: MeshLevelConfig(**params)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for name, params in raw["meshing"]["levels"].items()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for k in ["backend", "default_level", "element_type"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if k in raw["meshing"]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setattr(self.mesh, k, raw["meshing"][k])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if "geometry" in raw:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        geo = raw["geometry"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.geometry.output_format = geo.get("output_format", "step")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.geometry.freecad_path = geo.get("freecad_path")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if "validation" in geo:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.geometry.tolerance_mm = geo["validation"].get("tolerance_mm", 0.1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.geometry.blacklisted_operations = geo.get("blacklisted_operations", [])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if "simulation" in raw:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for k, v in raw["simulation"].items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if hasattr(self.simulation, k):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setattr(self.simulation, k, v)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if "batch" in raw:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for k, v in raw["batch"].items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if hasattr(self.batch, k):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setattr(self.batch, k, v)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if "output" in raw:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for k, v in raw["output"].items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if hasattr(self.output, k):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setattr(self.output, k, v)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def _resolve_env_vars(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Resolve environment variable references in config values."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if self.llm.api_key.startswith("${") and self.llm.api_key.endswith("}"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                env_var = self.llm.api_key[2:-1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.llm.api_key = os.environ.get(env_var, "")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not self.llm.api_key:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.llm.api_key = os.environ.get("GEMINI_API_KEY", "")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def get_mesh_level(self, level_name: str) -> MeshLevelConfig:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Get mesh level configuration by name."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if level_name in self.mesh.levels:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return self.mesh.levels[level_name]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return MeshLevelConfig()