"""
FeaGPT FastAPI Server
Serves FeaGPT as a REST API for Google Cloud Run / Firebase Hosting.

Endpoints:
    POST /analyze     - Submit NL description for FEA analysis
        POST /batch       - Submit parametric study
            GET  /status/{id} - Check job status
                GET  /results/{id}- Download results
                    GET  /health      - Health check
                    """

                    import os
                    import uuid
                    import json
                    import asyncio
                    import logging
                    from datetime import datetime
                    from typing import Optional
                    from pathlib import Path

                    from fastapi import FastAPI, HTTPException, BackgroundTasks
                    from fastapi.middleware.cors import CORSMiddleware
                    from fastapi.responses import JSONResponse, FileResponse
                    from pydantic import BaseModel, Field

                    # Setup logging
                    logging.basicConfig(level=logging.INFO)
                    logger = logging.getLogger("feagpt.api")

                    # Initialize FastAPI
                    app = FastAPI(
                        title="FeaGPT API",
                            description="Natural Language driven Finite Element Analysis",
                                version="0.1.0",
                                )

                                app.add_middleware(
                                    CORSMiddleware,
                                        allow_origins=["*"],
                                            allow_credentials=True,
                                                allow_methods=["*"],
                                                    allow_headers=["*"],
                                                    )

                                                    # In-memory job store (use Firestore in production)
                                                    jobs = {}

                                                    RESULTS_DIR = Path(os.environ.get("RESULTS_DIR", "results"))
                                                    RESULTS_DIR.mkdir(parents=True, exist_ok=True)


                                                    # ============================================================
                                                    # Request/Response Models
                                                    # ============================================================
                                                    class AnalyzeRequest(BaseModel):
                                                        description: str = Field(..., description="Natural language FEA description")
                                                            mesh_level: Optional[str] = Field("fine", description="Mesh density level")
                                                                config_override: Optional[dict] = Field(None, description="Config overrides")

                                                                class BatchRequest(BaseModel):
                                                                    description: str = Field(..., description="NL description with parameter ranges")
                                                                        max_configs: Optional[int] = Field(100, description="Max configurations to run")
                                                                            parallel_workers: Optional[int] = Field(4, description="Parallel workers")

                                                                            class JobStatus(BaseModel):
                                                                                job_id: str
                                                                                    status: str  # pending, running, completed, failed
                                                                                        progress: float = 0.0
                                                                                            created_at: str
                                                                                                completed_at: Optional[str] = None
                                                                                                    result_summary: Optional[dict] = None
                                                                                                        error: Optional[str] = None

                                                                                                        class AnalyzeResponse(BaseModel):
                                                                                                            job_id: str
                                                                                                                status: str
                                                                                                                    message: str


                                                                                                                    # ============================================================
                                                                                                                    # Background task: run FEA pipeline
                                                                                                                    # ============================================================
                                                                                                                    async def run_analysis(job_id: str, description: str, mesh_level: str):
                                                                                                                        """Execute GMSA pipeline in background."""
                                                                                                                            try:
                                                                                                                                    jobs[job_id]["status"] = "running"
                                                                                                                                            jobs[job_id]["progress"] = 0.1
                                                                                                                                                    logger.info(f"Job {job_id}: Starting analysis")

                                                                                                                                                            # Import pipeline
                                                                                                                                                                    from feagpt import GMSAPipeline, FeaGPTConfig

                                                                                                                                                                            config = FeaGPTConfig()
                                                                                                                                                                                    if os.path.exists("config.yaml"):
                                                                                                                                                                                                config = FeaGPTConfig("config.yaml")

                                                                                                                                                                                                        pipeline = GMSAPipeline(config)

                                                                                                                                                                                                                jobs[job_id]["progress"] = 0.2

                                                                                                                                                                                                                        # Run pipeline
                                                                                                                                                                                                                                result = await asyncio.to_thread(pipeline.run, description)

                                                                                                                                                                                                                                        jobs[job_id]["progress"] = 0.9

                                                                                                                                                                                                                                                # Save results
                                                                                                                                                                                                                                                        result_path = RESULTS_DIR / job_id
                                                                                                                                                                                                                                                                result_path.mkdir(parents=True, exist_ok=True)

                                                                                                                                                                                                                                                                        result_data = {
                                                                                                                                                                                                                                                                                    "job_id": job_id,
                                                                                                                                                                                                                                                                                                "description": description,
                                                                                                                                                                                                                                                                                                            "success": result.success if hasattr(result, 'success') else True,
                                                                                                                                                                                                                                                                                                                        "max_stress_mpa": getattr(result, 'max_stress', None),
                                                                                                                                                                                                                                                                                                                                    "max_displacement_mm": getattr(result, 'max_displacement', None),
                                                                                                                                                                                                                                                                                                                                                "num_elements": getattr(result, 'num_elements', None),
                                                                                                                                                                                                                                                                                                                                                            "num_nodes": getattr(result, 'num_nodes', None),
                                                                                                                                                                                                                                                                                                                                                                        "completed_at": datetime.utcnow().isoformat(),
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                        with open(result_path / "results.json", "w") as f:
                                                                                                                                                                                                                                                                                                                                                                                                    json.dump(result_data, f, indent=2, default=str)

                                                                                                                                                                                                                                                                                                                                                                                                            jobs[job_id]["status"] = "completed"
                                                                                                                                                                                                                                                                                                                                                                                                                    jobs[job_id]["progress"] = 1.0
                                                                                                                                                                                                                                                                                                                                                                                                                            jobs[job_id]["completed_at"] = datetime.utcnow().isoformat()
                                                                                                                                                                                                                                                                                                                                                                                                                                    jobs[job_id]["result_summary"] = result_data
                                                                                                                                                                                                                                                                                                                                                                                                                                            logger.info(f"Job {job_id}: Completed successfully")

                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        logger.error(f"Job {job_id}: Failed - {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                jobs[job_id]["status"] = "failed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        jobs[job_id]["error"] = str(e)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def run_batch_analysis(job_id: str, description: str, max_configs: int):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Execute batch parametric study in background."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        jobs[job_id]["status"] = "running"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.info(f"Batch job {job_id}: Starting")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from feagpt import GMSAPipeline, FeaGPTConfig

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                config = FeaGPTConfig()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if os.path.exists("config.yaml"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    config = FeaGPTConfig("config.yaml")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pipeline = GMSAPipeline(config)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result = await asyncio.to_thread(pipeline.run_batch, description, max_configs)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result_path = RESULTS_DIR / job_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result_path.mkdir(parents=True, exist_ok=True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            batch_data = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "job_id": job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "description": description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "num_configs": getattr(result, 'num_configs', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "success_rate": getattr(result, 'success_rate', 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "completed_at": datetime.utcnow().isoformat(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(result_path / "batch_results.json", "w") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    json.dump(batch_data, f, indent=2, default=str)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            jobs[job_id]["status"] = "completed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    jobs[job_id]["progress"] = 1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            jobs[job_id]["completed_at"] = datetime.utcnow().isoformat()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    jobs[job_id]["result_summary"] = batch_data

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.error(f"Batch job {job_id}: Failed - {str(e)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        jobs[job_id]["status"] = "failed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                jobs[job_id]["error"] = str(e)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # API Endpoints
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.get("/health")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async def health_check():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Health check endpoint for Cloud Run."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {"status": "healthy", "service": "feagpt", "version": "0.1.0"}


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.post("/analyze", response_model=AnalyzeResponse)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def analyze(request: AnalyzeRequest, background_tasks: BackgroundTasks):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Submit a natural language FEA analysis request."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                job_id = str(uuid.uuid4())[:8]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    jobs[job_id] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "job_id": job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "status": "pending",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "progress": 0.0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "created_at": datetime.utcnow().isoformat(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "description": request.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background_tasks.add_task(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            run_analysis, job_id, request.description, request.mesh_level
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return AnalyzeResponse(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            job_id=job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status="pending",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message=f"Analysis job {job_id} submitted. Poll /status/{job_id} for updates.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.post("/batch", response_model=AnalyzeResponse)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async def batch_analyze(request: BatchRequest, background_tasks: BackgroundTasks):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Submit a parametric batch study."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        job_id = f"batch-{str(uuid.uuid4())[:8]}"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            jobs[job_id] = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "job_id": job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "status": "pending",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "progress": 0.0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "created_at": datetime.utcnow().isoformat(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "description": request.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background_tasks.add_task(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    run_batch_analysis, job_id, request.description, request.max_configs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return AnalyzeResponse(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    job_id=job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status="pending",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message=f"Batch job {job_id} submitted with up to {request.max_configs} configs.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.get("/status/{job_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def get_status(job_id: str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Check job status."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if job_id not in jobs:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return jobs[job_id]


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @app.get("/results/{job_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def get_results(job_id: str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """Download job results."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if job_id not in jobs:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise HTTPException(status_code=404, detail=f"Job {job_id} not found")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if jobs[job_id]["status"] != "completed":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise HTTPException(status_code=400, detail=f"Job not yet completed: {jobs[job_id]['status']}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result_file = RESULTS_DIR / job_id / "results.json"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                batch_file = RESULTS_DIR / job_id / "batch_results.json"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if result_file.exists():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return FileResponse(result_file, media_type="application/json")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif batch_file.exists():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return FileResponse(batch_file, media_type="application/json")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise HTTPException(status_code=404, detail="Results file not found")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.get("/jobs")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def list_jobs():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """List all jobs."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {"jobs": list(jobs.values()), "total": len(jobs)}